### PR TITLE
Fix -- Uncaught Error: Cannot find module 'undefined'

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to
- https://github.com/GSA/catalog.data.gov/pull/612

Fixes

image

### CODE REVIEW

**Review by btylerburton — APPROVED** [review]
nice!

**Comment by jbrown-xentity** [comment]
We used to do this in a different way, don't know why it was removed: https://github.com/GSA/ckanext-datagovtheme/commit/8290c1748c82902c5fe4e3a4702e7d9861c9bcd4

**Comment by btylerburton** [comment]
We might be better off documenting exactly what each module is doing and evaluating each one to see if we can improve them, remove them, or leave them alone.

**Comment by nickumia-reisys** [comment]
Definitely should make that part of the design revamp, that's when we'll be doing most of the work with `datagovtheme` anyway

**Pull request merged**
