### PR TITLE
escapes meta tags & sanititzes publisher url

### PR DESCRIPTION
**Pull request by btylerburton**
Resolves https://github.com/GSA/data.gov/issues/4793

### CODE REVIEW

**Comment by btylerburton** [comment]
Added my other branch `update-dockerfile-and-deps` with dockerfile fixes as this one now fails to build...

**Review by jbrown-xentity — APPROVED** [review]
LGTM.
Any reason why we're changing from openknowledge to ckan for building the docker image?

**Comment by btylerburton** [comment]
@jbrown-xentity they've deprecated the open-knowledge one https://hub.docker.com/r/openknowledge/ckan-dev

**Comment by FuhuXia** [comment]
catalog.data.gov is working fine with Shapely==2.0.1.

**Pull request merged**
