### PR TITLE
4723 org link preview

### PR DESCRIPTION
**Pull request by robert-bryson**
Related to https://github.com/GSA/data.gov/issues/4723

### CODE REVIEW

**Comment by robert-bryson** [comment]
This is working correctly as is. Perhaps the cloudfront cache hadn't updated when looking before.

**Review by btylerburton — APPROVED** [review]
LGTM. I've got a couple non-blocking questions:

1. Is accessing properties of `c` object safe without a default? (i.e. c.pkg_dict or c.group_dict)
2. Is the outputted content what you want? Is it worth writing a test to prove it?

**Comment by FuhuXia** [comment]
> This is working correctly as is. Perhaps the cloudfront cache hadn't updated when looking before.

You means it is already deployed to prod?

**Comment by robert-bryson** [comment]
> LGTM. I've got a couple non-blocking questions:
> 
> 1. Is accessing properties of `c` object safe without a default? (i.e. c.pkg_dict or c.group_dict)

I'm not sure. The defaults set in lines 3-7 are to provide defaults in the case that a page is not a resource (e.g., has a `c.pkg_dict`) or an organization (e.g., has a `c.group_dict`), not explicitly for safety. That is, I suppose, a handy knock-on effect. I refactored to this approach to help avoid repeating code and improve legibility. 

> 2. Is the outputted content what you want? Is it worth writing a test to prove it?

Yes, it does appear correct. There is no good reason to not write a test, I suppose. It would be a best practice, certainly. I didn't partially out of speed and partially that if there is an issue with the `pkg` or `org` objects the defaults will fill in.

**Comment by robert-bryson** [comment]
Thanks for the review, @btylerburton and @FuhuXia!

**Comment by FuhuXia** [comment]
Test Org in development showing the right title. 
you can use https://catalog-dev.data.gov/organization/test-org?abc to bust the cache.
image

**Pull request merged**
