### PR TITLE
Go home

### PR DESCRIPTION
**Pull request by FuhuXia**
Logo should point to https://data.gov.

### CODE REVIEW

**Review by robert-bryson — DISMISSED** [review]

**Comment by FuhuXia** [comment]
@robert-bryson No need to worry about 2.10 for now.

**Comment by robert-bryson** [comment]
> @robert-bryson No need to worry about 2.10 for now.

I figured, I naively hoped that it was just a one-liner change.

**Comment by FuhuXia** [comment]
https://status.python.org/
Pypi publishing is failing.
```
[PyPI uploads are failing](https://status.python.org/incidents/yxsssbp9zh0v)
Our object storage provider is currently experiencing an outage, causing PyPI uploads to fail.
Apr 25, 20:44 UTC
```

**Comment by robert-bryson** [comment]
> 



> https://status.python.org/ Pypi publishing is failing.
> 
> ```
> [PyPI uploads are failing](https://status.python.org/incidents/yxsssbp9zh0v)
> Our object storage provider is currently experiencing an outage, causing PyPI uploads to fail.
> Apr 25, 20:44 UTC
> ```

Well that makes more sense than [this](https://github.com/GSA/ckanext-datagovtheme/pull/164). We should probably still do that, but an outage does make more sense. Good catch, @FuhuXia !

**Comment by FuhuXia** [comment]
Pypi is back, publishing is successful.

**Pull request merged**
